"""Subclass of Mainframe, which is generated by wxFormBuilder."""

import wx
import Automazione
from AutomazioneReportPerLuigiTrasformatoreExcelPanel import AutomazioneReportPerLuigiTrasformatoreExcelPanel
# Implementing Mainframe
class AutomazioneReportPerLuigiMainframe( Automazione.Mainframe ):
	def __init__( self, parent ):
		Automazione.Mainframe.__init__( self, parent )
		self.parent = parent
	# Handlers for Mainframe events.
	def OnMenuTrasformatore( self, event ):
		dlg = wx.TextEntryDialog(self.parent, 'Inserisci Password', 'Password', style = wx.TextEntryDialogStyle|wx.TE_PASSWORD)
		dlg.SetValue("Default")
		if dlg.ShowModal() == wx.ID_OK:
			if dlg.GetValue() != "16B64":
				wx.MessageBox("Password Sbagliata")
				dlg.Destroy()
			else:
				self.MainFrameNotebook.AddPage(AutomazioneReportPerLuigiTrasformatoreExcelPanel(self), "Trasformatore Excel")
				self.MainFrameNotebook.AdvanceSelection()



